# Usage:
# inside wasa2il/ copy local_settings.py-mysql-docker to local_settings.py
# docker-compose up
wasaweb:
  build: .
  volumes:
    - .:/usr/src/app
  ports:
    - "8000:8000"
  links:
    - "db"
db:
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=docker
    - MYSQL_DATABASE=docker
    - MYSQL_USER=docker
    - MYSQL_PASSWORD=docker
